name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install and Build 🏭
        run: |
          npm i
          npm run pre-build
          npm run build-ci
        env:
          LESSON_BUILDER_ENV: production

      - name: Deploy 📦
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
